# Generated by Django 3.2.9 on 2021-12-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_venda_data_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Entrega'),
        ),
    ]
